cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('comment/', include('comments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('p/<slug:slug>/', views.product_detail, name='product'),
    path('w/<int:pk>/', views.wish_product, name='wish'),
    path('store/', views.store, name='store'),
    path('checkout/', views.checkout, name='checkout'),
    path('to-bank/<int:order_id>/', views.to_bank, name='to_bank'),
    path('callback/', views.callback, name='callback'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_COUNT_CHOICES = [
    (number, str(number)) for number in range(1, 6)
]


class CartAddProductForm(forms.Form):
    product_count = forms.TypedChoiceField(
        choices=PRODUCT_COUNT_CHOICES,
        coerce=int,
        widget=forms.Select(
            attrs={
                'class': 'input-select',
            }
        )
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.core.handlers.wsgi import WSGIRequest
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_detail(request: WSGIRequest):
    cart = Cart(request)
    for item in cart:
        item['update_product_count_form'] = CartAddProductForm(
            initial={
                'product_count': item['product_count'],
                'update': True
            }
        )
    context = {
        'cart': cart
    }
    return render(request, 'cart/detail.html', context)


@require_POST
def cart_add(request: WSGIRequest, product_id: int):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart_data = form.cleaned_data
        cart.add(
            product=product,
            product_count=cart_data['product_count'],
            update_count=cart_data['update']
        )
    return redirect('cart:cart_detail')


def cart_remove(request: WSGIRequest, product_id: int):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load product %}

{% block title %}سبد خرید{% endblock title %}

{% block content %}
<h2>سبد خرید شما</h2>

<table class="cart table table-responsive table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-center">تصویر</th>
      <th scope="col" class="text-center">محصول</th>
      <th scope="col" class="text-center">تعداد</th>
      <th scope="col" class="text-center">حذف</th>
      <th scope="col" class="text-center">قیمت هر کدام</th>
      <th scope="col" class="text-center">قیمت کل</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
      {% with product=item.product %}
        <tr>
          <td class="order-img text-center">
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
          </td>
          <td class="text-center">{{ product.name }}</td>
          <td class="text-center">
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              {% csrf_token %}
              {{ item.update_product_count_form.product_count }}
              {{ item.update_product_count_form.update }}
              <input type="submit" value="آپدیت" />
            </form>
          </td>
          <td class="text-center">
            <a href="{% url 'cart:cart_remove' product.id %}">
              حذف
            </a>
          </td>
          <td class="num text-center">
            {{ item.price|comma }} تومان
          </td>
          <td class="num text-center">
            {{ item.total_price|comma }} تومان
          </td>
        </tr>
      {% endwith %}
    {% endfor %}
    <tr class="total">
      <td>قیمت کل</td>
      <td colspan="4"></td>
      <!-- TODO clear and total count -->
      <td class="num">
        {{ cart.get_total_price|comma }} تومان
      </td>
    </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url 'shop:store' %}" class="button light add-to-cart-btn">
    ادامه دادن به خرید
  </a>
  <a href="{% url 'shop:checkout' %}" class="button light">
    تصویه حساب
  </a>
</p>
{% endblock content %}