cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comment'
urlpatterns = [
    path(
        'product-comment/<int:pk>/',
        views.send_product_comment,
        name='product',
    ),
]

config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('comment/', include('comments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('p/<slug:slug>/', views.product_detail, name='product'),
    path('w/<int:pk>/', views.wish_product, name='wish'),
    path('store/', views.store, name='store'),
    path('checkout/', views.checkout, name='checkout'),
    path('to-bank/<int:order_id>/', views.to_bank, name='to_bank'),
    path('callback/', views.callback, name='callback'),
]

shop/models.py
from random import choices
from string import ascii_letters

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField

from comments.models import ProductComment


class Product(models.Model):
    name = models.CharField(
        max_length=128,
    )
    slug = models.CharField(
        max_length=4,
        editable=False,
        unique=True,
    )
    short_description = models.TextField()
    description = HTMLField()
    details = HTMLField()
    created_time = models.DateTimeField(
        auto_now_add=True,
    )
    updated_time = models.DateTimeField(
        auto_now=True,
    )
    image = models.ImageField(
        upload_to='images/product/%Y/%m/%d',
        blank=False,
        null=False,
    )
    price = models.BigIntegerField(
        default=10_000,
    )
    rate = models.FloatField(
        default=5,
        max_length=5,
    )
    stock_count = models.PositiveIntegerField(
        default=10,
    )
    sales = models.PositiveIntegerField(
        default=0,
    )

    def get_rating(self):
        INCREASER = 0.2
        rate = round(self.rate+INCREASER, 1)
        stars = int(rate // 1)
        float_rate = round(rate - stars, 1)
        half_stars = int(float_rate // 0.5)
        empty_stars = int(5 - (stars + (half_stars / 2)))
        return stars, half_stars, empty_stars

    def get_absolute_url(self):
        return reverse('shop:product', args=(self.slug,))

    def allow_to_send_comment(self, user) -> bool:
        return not ProductComment.objects.filter(
            user=user,
            product=self,
        ).exists()

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = self._random_slug(4)
            while Product.objects.filter(slug=slug).exists():
                slug = self._random_slug(4)
            self.slug = slug
        if self.rate > 5:
            self.rate = 5
        if self.rate < 0:
            self.rate = 0
        return super().save(*args, **kwargs)

    @staticmethod
    def _random_slug(length: int) -> str:
        return "".join(choices(ascii_letters, k=length))

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ('-created_time',)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        _("Images"),
        upload_to="images/product/%Y/%m/%d",
        blank=True,
    )

    def __str__(self) -> str:
        return self.image.url


class WishProduct(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )


class Order(models.Model):
    customer: User = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    order_time = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return f"{self.customer.username}'s order"

    class Meta:
        ordering = ('order_time',)
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        null=True,
        on_delete=models.SET_NULL,
    )
    product_price = models.IntegerField()
    product_count = models.PositiveIntegerField(
        default=1,
    )
    product_cost = models.IntegerField()

    def __str__(self) -> str:
        return f"order item {self.id}"

    class Meta:
        verbose_name = _('Order Item')
        verbose_name_plural = _('Order Items')


class Invoice(models.Model):
    order = models.ForeignKey(
        Order,
        null=True,
        on_delete=models.SET_NULL,
    )
    invoice_time = models.DateTimeField(
        auto_now_add=True,
    )
    authority = models.CharField(
        max_length=36,
        blank=True,
        null=True,
        unique=True,
    )

    def __str__(self) -> str:
        return f"invoice {self.id}"

    class Meta:
        ordering = ('invoice_time',)
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')


class Transaction(models.Model):
    class Status(models.TextChoices):
        PENDING = _('pending')
        FAILED = _('failed')
        COMPLETED = _('completed')

    invoice = models.ForeignKey(
        Invoice,
        null=True,
        on_delete=models.SET_NULL,
    )
    transaction_time = models.DateTimeField(
        auto_now_add=True,
    )
    amount = models.IntegerField()
    status = models.CharField(
        max_length=12,
        choices=Status.choices,
        default='pending',
    )

    def __str__(self) -> str:
        return f"transaction {self.id}"

    class Meta:
        ordering = ('transaction_time',)
        verbose_name = _('Transaction')
        verbose_name_plural = _('Transactions')

shop/views.py
from decimal import Decimal

from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.core.handlers.wsgi import WSGIRequest
from zeep import Client


from . import models
from cart.forms import CartAddProductForm
from cart.cart import Cart
from comments.forms import ProductCommentForm


merchant_code = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl/')


def index(request):
    context = {
        'latest_products': models.Product.objects.all()[:9],
        # TODO add selling number and best sell filter
        'best_selling_products': models.Product.objects.all()[:9],
    }
    return render(request, 'shop/index.html', context)


def product_detail(request: WSGIRequest, slug: str):
    product = get_object_or_404(models.Product, slug=slug)
    related_products = models.Product.objects.all()[:4]
    if request.user.is_authenticated and \
            product.allow_to_send_comment(request.user):
        comment_form = ProductCommentForm()
    else:
        comment_form = None
    comments = product.comments.filter(confirmed=True)
    context = {
        'product': product,
        'form': CartAddProductForm(),
        'related_products': related_products,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'shop/product-detail.html', context)


@login_required
def wish_product(request: WSGIRequest, pk: int):
    redirect_to = request.GET.get('next')
    product = get_object_or_404(models.Product, pk=pk)
    exists = models.WishProduct.objects.filter(
        product=product, user=request.user
    ).exists()
    if exists is False:
        models.WishProduct.objects.create(
            product=product,
            user=request.user,
        )
    if redirect_to is None:
        return redirect('shop:index')
    return redirect(redirect_to)


def store(request):
    return render(request, 'shop/store.html')


@login_required
def checkout(request: WSGIRequest):
    if request.method == 'POST':
        cart = Cart(request)
        order = models.Order.objects.create(
            customer=request.user
        )
        for item in cart:
            models.OrderItem.objects.create(
                order=order,
                product=item['product'],
                product_price=item['price'],
                product_count=item['product_count'],
                product_cost=int(Decimal(item['total_price']))
            )
        cart.clear()
        context = {
            'order': order,
        }
        return render(request, 'shop/order.html', context)
    return render(request, 'shop/checkout.html')


def to_bank(request: WSGIRequest, order_id):
    order = get_object_or_404(models.Order, id=order_id)
    if order.customer != request.user:
        raise Http404
    amount = sum(
        product['product_cost'] for product in
        models.OrderItem.objects.filter(
            order=order
        ).values('product_cost')
    )
    description = 'این یک تست است'
    email = ''
    mobile = ''
    callback_url = request.build_absolute_uri(reverse('shop:callback'))
    result = client.service.PaymentRequest(
        merchant_code,
        amount,
        description,
        email,
        mobile,
        callback_url
    )
    if result.Status == 100 and len(result.Authority) == 36:
        authority = result.Authority
        models.Invoice.objects.create(
            order=order,
            authority=authority
        )
        return redirect(f'https://www.zarinpal.com/pg/StartPay/{authority}')
    else:
        return HttpResponse(f'Error code: {result.Status}')


def callback(request: WSGIRequest):
    status = request.GET.get('Status')
    if status is not None and status == 'OK':
        authority = request.GET.get('Authority')
        invoice = get_object_or_404(
            models.Invoice,
            authority=authority
        )
        order = invoice.order
        amount = sum(
            product['product_cost'] for product in
            models.OrderItem.objects.filter(
                order=order
            ).values('product_cost')
        )
        result = client.service.PaymentVerification(
            merchant_code,
            authority,
            amount,
        )
        if result.Status == 100:
            context = {
                'invoice': invoice
            }
            return render(request, 'callback.html', context)
        else:
            return HttpResponse(f'Status Code: {result.Status}')
    else:
        return HttpResponse(f'Error: {status}')

shop/templates/shop/callback.html
{% extends 'base.html' %}

{% block title %}CallBack{% endblock title %}

{% block content %}
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 order-details">
        <div class="section-title text-center">
          <h3 class="title">Thank you</h3>
        </div>
        <div class="order-summary">
          <p>Your Invoice number: {{ invoice.id }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shop/templates/shop/order.html
{% extends "base.html" %}

{% block title %}Order{% endblock title %}

{% block content %}
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <span class="icon-check_circle display-3 text-success"></span>
        <h2 class="display-3 text-black">Thank you!</h2>
        <p class="lead mb-5">You order was successfully completed.</p>
        <p class="lead mb-5">Your Order Number : {{ order.id }}</p>
        <p>
          <a href="{% url 'shop:to_bank' order.id %}" class="primary-btn order-submit">
            Online Payment
          </a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shop/templates/shop/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% load product %}

{% block title %}{{ product.name}}{% endblock title %}

{% block content %}
<!-- NAVIGATION -->
<nav id="navigation">
  <!-- container -->
  <div class="container">
    <!-- responsive-nav -->
    <div id="responsive-nav">
      <!-- NAV -->
      <ul class="main-nav nav navbar-nav right reverse">
        <li class="active"><a href="#">خانه</a></li>
        <li><a href="#">برترین ها</a></li>
        <li><a href="#">پرفروش ترین ها</a></li>
        <li><a href="#">دسته بندی ها</a></li>
        <li><a href="#">کالای های دیجیتال</a></li>
        <li><a href="#">موبایل های هوشمند</a></li>
        <li><a href="#">لپ تاپ ها</a></li>
      </ul>
      <!-- /NAV -->
    </div>
    <!-- /responsive-nav -->
  </div>
  <!-- /container -->
</nav>
<!-- /NAVIGATION -->

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb-tree">
          <li><a href="#">خانه</a></li>
          <li><a href="#">تمام دسته بندی ها</a></li>
          <li><a href="#">تکنولوژی</a></li>
          <li><a href="#">موبایل</a></li>
          <li class="active">{{ product.name }}</li>
        </ul>
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!-- Product main img -->
      <div class="col-md-5 col-md-push-2">
        <div id="product-main-img">
          <div class="product-preview">
            <img src="{{ product.image.url }}" alt="" />
          </div>
          {% for productimage in product.productimage_set.all %}
          <div class="product-preview">
            <img src="{{ productimage.image.url }}" alt="" />
          </div>
          {% endfor %}
        </div>
      </div>
      <!-- /Product main img -->

      <!-- Product thumb imgs -->
      <div class="col-md-2 col-md-pull-5">
        <div id="product-imgs">
          <div class="product-preview">
            <img src="{{ product.image.url }}" alt="" />
          </div>
          {% for productimage in product.productimage_set.all %}
          <div class="product-preview">
            <img src="{{ productimage.image.url }}" alt="" />
          </div>
          {% endfor %}
        </div>
      </div>
      <!-- /Product thumb imgs -->

      <!-- Product details -->
      <div class="col-md-5">
        <div class="product-details">
          <h2 class="product-name">{{ product.name }}</h2>
          <div>
            <div class="product-rating">
              {{ product.get_rating|generate_rating|safe }}
            </div>
          </div>
          <div>
            <h3 class="product-price">
              <del class="product-old-price">990.00 تومان</del>
              <span>{{ product.price }} تومان</span>
            </h3>
          </div>
          <p>{{ product.short_description|linebreaks }}</p>

          <div class="product-options">
            <label>
              سایز
              <select class="input-select">
                <option value="0">X</option>
              </select>
            </label>
            <label>
              رنگ
              <select class="input-select">
                <option value="0">قرمز</option>
              </select>
            </label>
          </div>

          <div class="product-options add-to-cart">
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              <label> تعداد {{ form.product_count }} </label>
              {% csrf_token %}
              <button type="submit" class="add-to-cart-btn">
                <i class="fa fa-shopping-cart"></i>
                افزودن به سبد خرید
              </button>
            </form>
          </div>

          <ul class="product-btns">
            <li>
              <a href="{% url 'shop:wish' product.id %}?next={{ request.path }}"
                ><i class="fa fa-heart-o"></i>
                افزودن به علاقه مندی ها
              </a>
            </li>
          </ul>

          <ul class="product-links">
            <li>درسته بندی:</li>
            <li><a href="#">تکنولوژی</a></li>
            <li><a href="#">موبایل</a></li>
          </ul>

          <ul class="product-links">
            <li>اشتراک گذاری:</li>
            <li>
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-google-plus"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-envelope"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /Product details -->

      <!-- Product tab -->
      <div class="col-md-12">
        <div id="product-tab">
          <!-- product tab nav -->
          <ul class="tab-nav">
            <li class="active">
              <a data-toggle="tab" href="#tab1">توضیحات</a>
            </li>
            <li><a data-toggle="tab" href="#tab2">جزئیات</a></li>
            <li><a data-toggle="tab" href="#tab3">نظرات ({{ comment|length }})</a></li>
          </ul>
          <!-- /product tab nav -->

          <!-- product tab content -->
          <div class="tab-content">
            <!-- tab1  -->
            <div id="tab1" class="tab-pane fade in active">
              <div class="row">
                <div class="col-md-12">
                  <p>
                    {{ product.description|safe }}
                  </p>
                </div>
              </div>
            </div>
            <!-- /tab1  -->

            <!-- tab2  -->
            <div id="tab2" class="tab-pane fade in">
              <div class="row">
                <div class="col-md-12">
                  <p>
                    {{ product.details|safe }}
                  </p>
                </div>
              </div>
            </div>
            <!-- /tab2  -->

            <!-- tab3  -->
            <div id="tab3" class="tab-pane fade in">
              <div class="row">
                <!-- Review Form -->
                {% if comment_form %}
                  {% include 'shop/review.html' %}
                {% endif %}
                <!-- /Review Form -->
                <br>
                <br>
                <!-- Reviews -->
                <div class="col-md-12">
                  <div id="reviews">
                    <ul class="reviews">
                      {% for comment in comments %}
                      <li>
                        <div class="review-heading">
                          <h5 class="name">{{ comment.user.username }}</h5>
                          <!-- TODO use jalali date time -->
                          <p class="date">{{ comment.send_at }}</p>
                          <div class="review-rating">
                            {{ comment.get_rating|generate_rating|safe }}
                          </div>
                        </div>
                        <div class="review-body">
                          <p>
                            {{ comment.body }}
                          </p>
                        </div>
                      </li>
                      {% endfor %}
                    </ul>
                    <ul class="reviews-pagination">
                      <li class="active">1</li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li>
                        <a href="#"><i class="fa fa-angle-right"></i></a>
                      </li>
                    </ul>
                  </div>
                </div>
                <!-- /Reviews -->
              </div>
            </div>
            <!-- /tab3  -->
          </div>
          <!-- /product tab content  -->
        </div>
      </div>
      <!-- /product tab -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->

<!-- Section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <div class="col-md-12">
        <div class="section-title text-center">
          <h3 class="title">محصولات مرتبط</h3>
        </div>
      </div>
      {% for product in related_products %}
        <!-- product -->
        <div class="col-md-3 col-xs-6">
          {% include 'shop/product.html' %}
        </div>
        <!-- /product -->
      {% endfor %}
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /Section -->
{% endblock content %}

shop/templates/shop/product-widget.html
<div class="product-widget">
  <a href="{{ product.get_absolute_url }}">
    <div class="product-img">
      <img src="{{ product.image.url }}" alt="" />
    </div>
    <div class="product-body">
      <p class="product-category">دسته بندی</p>
      <h3 class="product-name">
        <a href="{{ product.get_absolute_url }}"> {{ product.name }} </a>
      </h3>
      <h4 class="product-price">
        <del class="product-old-price">3،000،000 تومان</del>
        <span>{{ product.price }} تومان</span>
      </h4>
    </div>
  </a>
</div>

shop/templates/shop/product.html
{% load product %}
<!-- product -->
<div class="product">
  <div class="product-img">
    <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
      <img
        src="{{ product.image.url }}"
        alt="{{ product.name }}"
        title="{{ product.name }}"
      />
    </a>
    <div class="product-label ltr">
      <span class="sale"> -30% </span>
      <span class="new">جدید</span>
    </div>
  </div>
  <div class="product-body">
    <!-- TODO add category to product -->
    <p class="product-category">دسته بندی</p>
    <h3 class="product-name">
      <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
        {{ product.name }}
      </a>
    </h3>
    <h4 class="product-price">
      <!-- TODO add discount to product -->
      <del class="product-old-price">3،000،000 تومان</del>
      <br />
      <span>{{ product.price }} تومان</span>
    </h4>
    <div class="product-rating">
      {{ product.get_rating|generate_rating|safe }}
    </div>
    <div class="product-btns">
      <a
        class="add-to-wishlist"
        href="{% url 'shop:wish' product.id %}?next={{ request.path }}"
      >
        <i class="fa fa-heart-o"></i>
        <span class="tooltipp"> اضافه کردن به علاقه مندی ها </span>
      </a>
      <a class="quick-view" href="{{ product.get_absolute_url }}">
        <i class="fa fa-eye"></i>
        <span class="tooltipp"> دیدن محصول </span>
      </a>
    </div>
  </div>
  <div class="add-to-cart">
    <button class="add-to-cart-btn">
      <i class="fa fa-shopping-cart"></i>
      افزودن به سبد خرید
    </button>
  </div>
</div>
<!-- /product -->

shop/templates/shop/review.html
<div class="col-md-12">
  <div class="row">
    <div class="col-md-6">
      <div id="review-form">
        <form
          action="{% url 'comment:product' product.id %}"
          class="review-form"
          method="post"
        >
          {{ comment_form.body }}
          <div class="input-rating">
            <span>امتیاز شما: </span>
            <div class="stars">
              <input id="star5" name="rate" value="5" type="radio" /><label
                for="star5"
              ></label>
              <input id="star4" name="rate" value="4" type="radio" /><label
                for="star4"
              ></label>
              <input id="star3" name="rate" value="3" type="radio" /><label
                for="star3"
              ></label>
              <input id="star2" name="rate" value="2" type="radio" /><label
                for="star2"
              ></label>
              <input id="star1" name="rate" value="1" type="radio" /><label
                for="star1"
              ></label>
            </div>
          </div>
          <button class="primary-btn">ارسال</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>